In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:/Users/kyu11/Documents/GitHub/python/csv/Nutrition_Value_Dataset.csv')
print(df)

data = pd.DataFrame(df)

       Company   Category                           Product Per Serve Size  \
0    Pizza Hut  All Meals          Corn n Cheese (Personal)        143.5 g
1    Pizza Hut  All Meals          Country Feast (Personal)          178 g
2    Pizza Hut  All Meals          Double Cheese (Personal)          143 g
3    Pizza Hut  All Meals  Double Paneer Supreme (Personal)        174.5 g
4    Pizza Hut  All Meals          Farmer`s Pick (Personal)          177 g
..         ...        ...                               ...            ...
525    Dominos  All Meals                    CHICKEN WINGS           174.0
526    Dominos  All Meals            CRISPY CHICKEN STRIPS           156.0
527    Dominos  All Meals             ZINGY PARCEL CHICKEN           210.0
528    Dominos  All Meals          TACO MEXICANA - CHICKEN            97.0
529    Dominos  All Meals        CALZONE POCKETS - CHICKEN           248.0

     Energy (kCal)  Carbohydrates (g)  Protein (g)  Fiber (g)  Sugar (g)  \
0           432.60              65.64        17.91       3.85        0.0
1           407.60              67.11        16.73       7.19        0.0
2           423.33              59.97        18.26       3.49        0.0
3           474.03              52.86        20.07       3.79        0.0
4           408.16              53.93        19.91       2.46        0.0
..             ...                ...          ...        ...        ...
525         352.90              24.50        35.30       5.76       10.4
526         461.20              51.30        26.70       5.16        3.6
527         667.50              17.30        19.20      16.92       10.6
528         322.60              34.20         9.30       5.40        3.9
529         582.90             101.00        18.60       5.04       12.2

     Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  Cholesterol (mg)  \
0            10.93               5.14           0.16             16.19
1             8.03               3.24           0.11             66.80
2            12.27               5.23           0.18             19.75
3            20.26               9.25           0.33             71.72
4            12.53               4.90           0.14             48.09
..             ...                ...            ...               ...
525          12.60               4.80           0.19            308.70
526          13.90               4.30           0.17            713.07
527          31.30              14.10           0.56            541.49
528          16.50               4.50           0.18            564.30
529          11.60               4.20           0.17           1171.60

     Sodium (mg)
0         499.72
1         818.00
2         638.22
3        1128.11
4         942.67
..           ...
525          NaN
526          NaN
527          NaN
528          NaN
529          NaN

[530 rows x 14 columns]

In [4]:
import os
print(os.getcwd())

c:\Users\kyu11\Documents\GitHub\python\23.01.28\fastfood_nutrition

In [5]:
df

,Company,Category,Product,Per Serve Size,Energy (kCal),Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg)
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,3.79,0.0,20.26,9.25,0.33,71.72,1128.11
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,2.46,0.0,12.53,4.90,0.14,48.09,942.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Dominos,All Meals,CHICKEN WINGS,174.0,352.90,24.50,35.30,5.76,10.4,12.60,4.80,0.19,308.70,NaN
526,Dominos,All Meals,CRISPY CHICKEN STRIPS,156.0,461.20,51.30,26.70,5.16,3.6,13.90,4.30,0.17,713.07,NaN
527,Dominos,All Meals,ZINGY PARCEL CHICKEN,210.0,667.50,17.30,19.20,16.92,10.6,31.30,14.10,0.56,541.49,NaN
528,Dominos,All Meals,TACO MEXICANA - CHICKEN,97.0,322.60,34.20,9.30,5.40,3.9,16.50,4.50,0.18,564.30,NaN
529,Dominos,All Meals,CALZONE POCKETS - CHICKEN,248.0,582.90,101.00,18.60,5.04,12.2,11.60,4.20,0.17,1171.60,NaN

In [35]:
new_column_names = {
    'Per Serve Size': 'per_serve_size',
    'Energy (kCal)': 'energy_kcal',
    'Carbohydrates (g)': 'carbohydrate_g',
    'Protein (g)' : 'Protein_g',
    'Fiber (g)':'Fiber_g',
    'Sugar (g)' : 'Sugar_g',
    'Total Fat (g)':'Total_Fat_g',
    'Saturated Fat (g)':'Saturated_Fat_g',
    'Trans Fat (g)':'Trans_Fat_g' ,
    'Cholesterol (mg)': 'Cholesterol_mg',
    'Sodium (mg)':'Sodium_mg'
}

df.rename(columns=new_column_names, inplace=True)

In [37]:
df

,Company,Category,Product,per_serve_size,energy_kcal,carbohydrate_g,Protein_g,Fiber_g,Sugar_g,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,3.79,0.0,20.26,9.25,0.33,71.72,1128.11
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,2.46,0.0,12.53,4.90,0.14,48.09,942.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Dominos,All Meals,CHICKEN WINGS,174.0,352.90,24.50,35.30,5.76,10.4,12.60,4.80,0.19,308.70,NaN
526,Dominos,All Meals,CRISPY CHICKEN STRIPS,156.0,461.20,51.30,26.70,5.16,3.6,13.90,4.30,0.17,713.07,NaN
527,Dominos,All Meals,ZINGY PARCEL CHICKEN,210.0,667.50,17.30,19.20,16.92,10.6,31.30,14.10,0.56,541.49,NaN
528,Dominos,All Meals,TACO MEXICANA - CHICKEN,97.0,322.60,34.20,9.30,5.40,3.9,16.50,4.50,0.18,564.30,NaN
529,Dominos,All Meals,CALZONE POCKETS - CHICKEN,248.0,582.90,101.00,18.60,5.04,12.2,11.60,4.20,0.17,1171.60,NaN

In [38]:
sodium = float(input("Enter the sodium amount: "))
serve_size = float(input("Enter the serving size: "))

result = (sodium * 100) / serve_size

print("The result is:", result)

ValueError: could not convert string to float: ''

In [41]:
max_sodium_index = df['Sodium_mg'].idxmax()
product_with_highest_sodium = df.loc[max_sodium_index, 'Product']

print("Product with the highest sodium:", product_with_highest_sodium)

Product with the highest sodium: Ghee Rice with Mc Spicy Fried Chicken 1 pc

In [47]:
df['sodium_percent'] = (df['Sodium_mg'] * 100) / df['per_serve_size']

result = df.groupby(['product','Company'])['Sodium_mg'].mean().reset_index()
result = result.sort_values(by='sodium_percent')

print(result)

TypeError: unsupported operand type(s) for /: 'float' and 'str'